"""Add approved column to BlogPost

Revision ID: 40a40ab0d36d
Revises: e3da3dac2e2a
Create Date: 2025-10-15 17:12:04.235279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a40ab0d36d'
down_revision = 'e3da3dac2e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
