"""Add approved column to BlogPost

Revision ID: 475145f93bad
Revises: 40a40ab0d36d
Create Date: 2025-10-15 17:19:34.843584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475145f93bad'
down_revision = '40a40ab0d36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
